import PropTypes from 'prop-types'

export const termType = {
  iri: PropTypes.string.isRequired,
  label: PropTypes.string.isRequired,
  description: PropTypes.string,
  annotation: PropTypes.shape({
    seeAlso: PropTypes.arrayOf(PropTypes.string)
  }),
  synonyms: PropTypes.bool,
  ontology_name: PropTypes.string,
  ontology_prefix: PropTypes.string,
  ontology_iri: PropTypes.string,
  is_obsolete: PropTypes.bool,
  term_replaced_by: PropTypes.string,
  is_defining_ontology: PropTypes.bool,
  has_children: PropTypes.bool,
  is_root: PropTypes.bool,
  short_form: PropTypes.string,
  obo_id: PropTypes.string,
  in_subset: PropTypes.bool,
  obo_definition_citation: PropTypes.string,
  obo_xref: PropTypes.string,
  obo_synonym: PropTypes.string,
  is_preferred_root: PropTypes.bool,
  _links: PropTypes.shape({
    self: PropTypes.string.isRequired,
    parents: PropTypes.string.isRequired,
    ancestors: PropTypes.string.isRequired,
    hierarchicalParents: PropTypes.string.isRequired,
    hierarchicalAncestors: PropTypes.string.isRequired,
    jstree: PropTypes.string.isRequired,
    graph: PropTypes.string.isRequired,
  }),
  id: PropTypes.string,
  seeAlso: PropTypes.arrayOf(PropTypes.string),
}

export const termDefaults = {
  iri: '',
  label: '',
  description: '',
  annotation: {
    seeAlso: [],
  },
  synonyms: null,
  ontology_name: '',
  ontology_prefix: '',
  ontology_iri: '',
  is_obsolete: false,
  term_replaced_by: '',
  is_defining_ontology: false,
  has_children: false,
  is_root: false,
  short_form: '',
  obo_id: '',
  in_subset: false,
  obo_definition_citation: '',
  obo_xref: '',
  obo_synonym: '',
  is_preferred_root: false,
  _links: {
    self: '',
    parents: '',
    ancestors: '',
    hierarchicalParents: '',
    hierarchicalAncestors: '',
    jstree: '',
    graph: '',
  },
  id: '',
}